name: CI - Cargo Tracker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Backend
      - name: Setup Node.js (Backend)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies (Backend)
        run: |
          cd backend
          npm install

      - name: Run Backend Lint/Test
        run: |
          cd backend
          npm run lint || echo "No lint script"
          npm test || echo "No test script"

      # Frontend
      - name: Setup Node.js (Frontend)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: webapp/package-lock.json

      - name: Install dependencies (Frontend)
        run: |
          cd webapp
          npm install

      - name: Build Frontend
        run: |
          cd webapp
          npm run build
